---
- name: Installing and starting Nginx on Ubuntu
  hosts: all
  become: yes
  
  tasks:
    - name: Updating package list
      apt:
        update_cache: yes

    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Starting the Nginx service
      service:
        name: nginx
        state: started
        enabled: yes